//actions for login users;

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

//action for cart items;

export const ADD_CART_ITEM_REQUEST = "ADD_CART_ITEM_REQUEST";
export const ADD_CART_ITEM_SUCCESS = "ADD_CART_ITEM_SUCCESS";
export const ADD_CART_ITEM_FAILURE = "ADD_CART_ITEM_FAILURE";

export const UPDATE_CART_ITEM_REQUEST = "UPDATE_CART_ITEM_REQUEST";
export const UPDATE_CART_ITEM_SUCCESS = "UPDATE_CART_ITEM_SUCCESS";
export const UPDATE_CART_ITEM_FAILURE = "UPDATE_CART_ITEM_FAILURE";


export const DELET_CART_ITEM_REQUEST = "DELET_CART_ITEM_REQUEST";
export const DELET_CART_ITEM_SUCCESS = "DELET_CART_ITEM_SUCCESS";
export const DELET_CART_ITEM_FAILURE = "DELET_CART_ITEM_FAILURE";


export const LOGOUT = "LOGOUT";


//action for labtest item